#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  ALTER DATABASE ${POSTGRES_DB} SET timezone TO 'UTC';

  CREATE EXTENSION IF NOT EXISTS pgcrypto;

  CREATE ROLE ${MIGRATE_DB_USER} LOGIN PASSWORD '${MIGRATE_DB_PASSWORD}';
  CREATE ROLE ${APP_DB_USER} LOGIN PASSWORD '${APP_DB_PASSWORD}';

  GRANT CONNECT, CREATE ON DATABASE ${POSTGRES_DB} TO ${MIGRATE_DB_USER};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER};

  GRANT USAGE, CREATE ON SCHEMA public TO ${MIGRATE_DB_USER};
  GRANT USAGE ON SCHEMA public TO ${APP_DB_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATE_DB_USER} IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_DB_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATE_DB_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${APP_DB_USER};

  ALTER ROLE ${MIGRATE_DB_USER} SET search_path TO public;
  ALTER ROLE ${APP_DB_USER} SET search_path TO public;
EOSQL
